version: '3.7'
services:
  prom:
    image: prom/prometheus
    restart: always
    network_mode: host
    container_name: prom
    command: ["--config.file=/conf/prometheus.yml",
              "--storage.tsdb.retention=30d",
              "--web.listen-address=10.247.21.83:9090",
              "--web.enable-lifecycle"]
    volumes:
      - ./conf:/conf
      - /var/data/prometheus_data:/prometheus

