version: '3.9'
services:
  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    hostname: grafana
    environment:
            #    GF_SMTP_ENABLED: true
            #GF_SMTP_HOST: 10.9.97.27:25
            #GF_SMTP_FROM_ADDRESS: <emailaddress>
            #GF_SMTP_FROM_NAME: Grafana-
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  

  renderer:
    image: grafana/grafana-image-renderer:3.4.1 
    container_name: renderer
    hostname: renderer
    restart: always
    ports:
      - 8081
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

