# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.247.21.83:9090']

  - job_name: 'node-exporter_ktbcs_bac'
    static_configs:
    #node_exporter
      - targets: ['10.247.40.240:9100']
      - targets: ['10.247.40.241:9100']
      - targets: ['10.247.40.242:9100']
      - targets: ['10.247.40.243:9100']
      - targets: ['10.247.41.242:9100']

        #  - job_name: 'opensearch_exporter'
        #    scheme: https
        #    scrape_interval: 10s
        #    metrics_path: "/_prometheus/metrics"
        #    static_configs:
    #opensearch
    #      - targets: ['10.247.40.243:9200']
    #      - targets: ['10.247.40.244:9200']
    #      - targets: ['10.247.40.245:9200']
    #    basic_auth:
    #      username: 'admin'
    #      password: 'admin'
    #    tls_config:
    #      insecure_skip_verify: true



  - job_name: 'kong'
    static_configs:
      #kong
      - targets: ['10.247.40.240:8001']
      - targets: ['10.247.40.241:8001']
     

  - job_name: 'cassandra'
    static_configs:
      #cassandra
      - targets: ['10.247.41.240:8080']
      - targets: ['10.247.41.241:8080']
      - targets: ['10.247.41.242:8080']

   
        #  - job_name: 'opensearch'
        #    static_configs:
      #opensearch
      #      - targets: ['10.247.40.243:9114']
      #      - targets: ['10.247.40.244:9114']
      #      - targets: ['10.247.40.245:9114']

        #   static_configs:
      #opensearch
      #      - targets: ['10.247.42.243:9114']
      #      - targets: ['10.247.42.244:9114']
      #      - targets: ['10.247.42.245:9114']


        #  - job_name: 'opensearch_exporter'
        #    scheme: https
        #    scrape_interval: 10s
        #    metrics_path: "/_prometheus/metrics"
        #    static_configs:
    #opensearch exporter
    #      - targets: ['10.247.42.243:9200']
    #      - targets: ['10.247.42.244:9200']
    #      - targets: ['10.247.42.245:9200']
    #    basic_auth:
    #      username: 'admin'
    #      password: 'admin'
    #    tls_config:
    #      insecure_skip_verify: true

